# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: models.llama3_2_1b_clevr3d_sin_cos_plus_learned_numbers

checkpointer:
  _component_: checkpointer.FullModelMetaCheckpointer3D
  convert_weights_type: 3d_sin_cos_plus_learned_num
  checkpoint_dir: ./checkpoints/clevr/recognition/
  checkpoint_files: [
    meta_model_9.pt
  ]
  output_dir: ./checkpoints/clevr/recognition-inference-colab-demo
  model_type: LLAMA3_2

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ./llama-3-models/Llama3.2-1B-Instruct/tokenizer.model


instruct_template: null
chat_format: null
max_new_tokens: 2500
temperature: 1.0
# top_k: 300

load_text_data: False
load_image_data: True
load_three_d_data: True
load_text_target_data: False
load_image_target_data: False
load_three_d_target_data: False

image_file: "./3d-mllm-datasets-and-codebooks/pretokenized-data/clevr/images/test_vqgan_indices_merged_for_rendering_and_recognition.json"
image_target_file: "./3d-mllm-datasets-and-codebooks/pretokenized-data/clevr/images/test_vqgan_indices_merged_for_rendering_and_recognition.json"

text_file: "./3d-mllm-datasets-and-codebooks/pretokenized-data/clevr/3d-scenes/test_tokenized_scenes_merged_for_rendering_and_recognition.json"
three_d_file: "./3d-mllm-datasets-and-codebooks/pretokenized-data/clevr/3d-scenes/test_tokenized_scenes_merged_for_rendering_and_recognition.json"
three_d_target_file: "./3d-mllm-datasets-and-codebooks/pretokenized-data/clevr/3d-scenes/test_tokenized_scenes_merged_for_rendering_and_recognition.json"

run_identifier: "clevr_recognition_inference"
image_embeddings_output_folder: "./checkpoints/clevr/recognition-inference-colab-demo/image_embeddings"
three_d_json_output_folder: "./checkpoints/clevr/recognition-inference-colab-demo/three_d_json"

dataset_name: "CLEVR"
vqgan_type: "clevr"
vqgan_row_col_size: 16
reorder_image_tokens: False
task_type: "I-3"
num_samples: -1
sample_start_idx: 0 
image_token_offset: 129471

# enable_kv_cache: True

quantizer: null

