# Config for running the InferenceRecipe in generate.py to generate output from an LLM
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

# Model arguments
model:
  _component_: models.llama3_2_1b_clevr3d_sin_cos_plus_learned_numbers

checkpointer:
  _component_: checkpointer.FullModelMetaCheckpointer3D
  convert_weights_type: 3d_sin_cos_plus_learned_num
  checkpoint_dir: ./checkpoints/clevr/instruction-following/
  checkpoint_files: [
    meta_model_9.pt
  ]
  output_dir: ./checkpoints/clevr/instruction-following-inference
  model_type: LLAMA3_2

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ./llama-3-models/Llama3.2-1B-Instruct/tokenizer.model


instruct_template: null
chat_format: null
max_new_tokens: 2500
temperature: 1.0
# top_k: 300

load_text_data: True
load_image_data: True
load_three_d_data: True
load_text_target_data: False
load_image_target_data: True
load_three_d_target_data: True

image_file: "./kyvo-datasets-and-codebooks/pretokenized-data/clevr/images/instruction-following-eval-source/test_vqgan_indices_removal_with_relation.json"
image_target_file: "./kyvo-datasets-and-codebooks/pretokenized-data/clevr/images/instruction-following-eval-target/test_vqgan_indices_removal_with_relation.json"

text_file: "./kyvo-datasets-and-codebooks/pretokenized-data/clevr/text/instruction-following-eval/test_text_instructions_removal_with_relation.json"
three_d_file: "./kyvo-datasets-and-codebooks/pretokenized-data/clevr/3d-scenes/instruction-following-eval-source/test_tokenized_scenes_removal_with_relation.json"
three_d_target_file: "./kyvo-datasets-and-codebooks/pretokenized-data/clevr/3d-scenes/instruction-following-eval-target/test_tokenized_scenes_removal_with_relation.json"

run_identifier: "clevr_instruction-following-removal-with-relation_inference"
image_embeddings_output_folder: "./checkpoints/clevr/instruction-following-inference/image_embeddings"
three_d_json_output_folder: "./checkpoints/clevr/instruction-following-inference/three_d_json"

dataset_name: "CLEVR"
vqgan_type: "clevr"
vqgan_row_col_size: 16
reorder_image_tokens: True
task_type: "I+3+T-I+3"
num_samples: -1
sample_start_idx: 0
image_token_offset: 129471

# enable_kv_cache: True

quantizer: null
